version: "3.7"
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: books
    volumes:
      - ./docker-volumes/db/mysql:/var/lib/mysql
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql:ro
    ports:
      - 33306:3306

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    environment:
      - PMA_HOST=db
    restart: always
    ports:
      - 18080:80
    volumes:
      - /sessions